name: ci

on:
pull_request:
branches: [ "main" ]
push:
branches: [ "main" ]

permissions:
contents: read
packages: write

env:
IMAGE_NAME: ghcr.io/${{ github.repository }}/app

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Build image
    uses: docker/build-push-action@v6
    with:
      context: .
      file: ./Dockerfile
      push: false
      tags: app:${{ github.sha }}
